[INFO main 26] Initialising Python Geth Console...
[INFO main 32] Initialising peer buffer...
[INFO main 32] Initialising TCP server...
[INFO main 32] Initialising RandB board...
[INFO main 32] Initialising ground-sensors...
[INFO main 33] Initialising random-walk...
[INFO main 4970] Starting Experiment
[INFO main 7002] Added peer: 3, enode: enode://cb6ef100ffa12fca6c0651dce5537c88be53f8a17f6fa69b895a82b20f5e196d56cd32c619abf29dbe94be271a61b964ea492bc3bbab6b6c124d69e11f8f41d7@10.0.1.5:30303?discport=0
[INFO main 7013] Added peer: 4, enode: enode://d51aa01553b2e23c35f0f69dedfbbd2934f67894f9b9f046103d14930f49bc58e32cd423e5f54a9ba831a0c9677ed9da0c6c28c1239cea4aa03085be655c1c47@10.0.1.6:30303?discport=0
[INFO main 8045] Added peer: 6, enode: enode://4f5f859718b5e9c41d69ebf2c0d1ddd2b8e6c794d34c8a338c44c226409792d0af425e98708dce0c82085952dc76b8abc3f8de64062c403eb96bc11ac34c20b3@10.0.1.8:30303?discport=0
[DEBUG events 12051] 0x0000000000000000000000000000000000000000
[DEBUG events 12058] Registered on-chain
[WARNING events 16038] execution reverted: Robot must register first

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/rpyc/core/protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python3.8/site-packages/rpyc/core/protocol.py", line 592, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/root/python_scripts/web3wrapper_docker.py", line 157, in exposed_call
    return self.w3if.call(function)
  File "/root/python_scripts/web3wrapper_docker.py", line 92, in call
    return getattr(self.sc.functions, func)().call()
  File "/usr/lib/python3.8/site-packages/web3/contract.py", line 957, in call
    return call_contract_function(
  File "/usr/lib/python3.8/site-packages/web3/contract.py", line 1501, in call_contract_function
    return_data = web3.eth.call(
  File "/usr/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 167, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/usr/lib/python3.8/site-packages/web3/manager.py", line 67, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/usr/lib/python3.8/site-packages/web3/_utils/method_formatters.py", line 566, in raise_solidity_error_on_revert
    raise ContractLogicError(response['error']['message'])
web3.exceptions.ContractLogicError: execution reverted: Robot must register first

[INFO main 17051] Removed peer: 6
[INFO main 22047] Added peer: 6, enode: enode://4f5f859718b5e9c41d69ebf2c0d1ddd2b8e6c794d34c8a338c44c226409792d0af425e98708dce0c82085952dc76b8abc3f8de64062c403eb96bc11ac34c20b3@10.0.1.8:30303?discport=0
[INFO main 22058] Removed peer: 4
[DEBUG events 29044] 0x26CbcaC5281B6E159bc3e6C7400AF25fA46F246B
[INFO main 29051] Added peer: 1, enode: enode://6bb18517035c4ad2668fbcb450a1dd84af49270dc8c395208e4fe979bc97a90338cae69cce9e3502e4c116a258c1a2a6d56ff61915269bb7fd079b56440556a3@10.0.1.3:30303?discport=0
[DEBUG events 29053] Registered on-chain
[INFO main 30046] Added peer: 2, enode: enode://dad2cb74f9b1c591cdc92fec9a8c0835eb06e2ce882ff4451d22a2853719ddc76f6bc30d66e48c2af901b944c41f04b451bb7ea21c86c9c974249c09f705eb69@10.0.1.4:30303?discport=0
[INFO main 32033] Removed peer: 3
[DEBUG events 37082] Asked for UBI: 40
